#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx 

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/index.html

# Restart nginx
sudo service nginx restart
