#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

sudo touch /var/www/html/index.html  
echo "Holberton School" | sudo tee /var/www/index.html

# Restart nginx
sudo service nginx restart
